services:
  - type: web
    name: bizmodelai
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    domains:
      - www.bizmodelai.com

  - type: pserv
    name: bizmodelai-db
    env: postgres
    plan: starter
    ipAllowList: []
    maxConnections: 20
